### ISSUE TITLE
Поддержка Symfony 5.x / Symfony 5.x support

### ISSUE THREAD

**Issue by anomality** [pvsaintpe/ltree-bundle#3]
Здравствуйте!
Можно ли надеяться, что бандл будет доступен для 5-й ветки Symfony?

**Comment by pvsaintpe** [comment]
Смотрите, я не адаптировал его под новые версии так как еще не переходил на 5-ку. Вы можете кинуть PR? Я его вмержу

**Comment by anomality** [comment]
Боюсь, моих знаний на это не хватит )

**Comment by pvsaintpe** [comment]
Ну нет, это же не сложно, во первых нужно решить проблему наследования, то как реализован репозиторий сейчас не оч хороший путь.

во вторых посмотреть в чем несовместимость бандлов для 4.3 и 5-ки

я думаю там минимум дело в композер

Как максимум в изменении пары компонентов

вы попробуйте а если что я вам помогу

**Comment by pvsaintpe** [comment]
> Боюсь, моих знаний на это не хватит )

Ну что рискнете?

**Comment by anomality** [comment]
давайте попробую. надо же когда-то начинать

**Comment by pvsaintpe** [comment]
> давайте попробую. надо же когда-то начинать

Давайте начнем с ошибок, сделайте форк склонируйте репозиторий и добавьте в композер версию симфони 5-ую например так 

^4.3|^5.0

Создайте ветку и пушните

а в своем проекте в composer.json укажите зависимость на пакет и вместо версии укажите название вашей ветки и  через 

`
"repositories": [
    {
       "type": "vcs",
       "url": "укажите путь к вашему форкнутому репозиторию начинаться будет с git@github... а на конце будет .git"
    }
]
`

В своем проекте запустите `composer update pvsaintpe/ltree-bundle`

И посмотрите какие будут ошибки

пушните их сюда и посмотрим что можно сделать

**Comment by pvsaintpe** [comment]
Added support Symfony 5 at v2.0.0
